return {
  {
    "catppuccin/nvim",
    enabled = true,
    name = "catppuccin",
    priority = 1000,
    opts = {
      transparent_background = true,
      integrations = {
        alpha = true,
        aerial = true,
        dap = { enabled = true, enable_ui = true },
        barbar = true,
        mason = true,
        neotree = true,
        notify = true,
        nvimtree = false,
        semantic_tokens = true,
        symbols_outline = true,
        telescope = true,
        ts_rainbow = false,
        harpoon = true,
        sandwich = false,
        noice = true,
        mini = true,
        leap = true,
        markdown = true,
        neotest = true,
        cmp = {
          enabled = true,
          border = true,
        },
        overseer = true,
        lsp_trouble = true,
        rainbow_delimiters = false,
        gitsigns = true,
        notifier = true,
        dashboard = true,
        navic = { enabled = true, custom_bg = "lualine" },
        treesitter = true,
        which_key = true,
        native_lsp = {
          enabled = true,
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
        flash = true,
        illuminate = true,
        indent_blankline = { enabled = true },
      },
    },
  },
  -- {
  --   "nvim-telescope/telescope.nvim",
  --   optional = true,
  --   opts = {
  --     highlight = {
  --       enable = true,
  --       additional_vim_regex_highlighting = false,
  --     },
  --   },
  -- },
}
